#include "drv8323.h"


/* SPI1 handle is generated by CubeMX */
extern SPI_HandleTypeDef hspi1;
uint8_t drv_cs_debug;
uint16_t drv_write_rx;

/*
 * DRV8323 power-on default register values.
 *
 * 注意：
 * 这些值只适合用于上电后、尚未修改配置寄存器时的检查。
 */
static const uint8_t check_addr[] =
{
    DRV8323_REG_CTRL,
    DRV8323_REG_GATE_HS,
    DRV8323_REG_GATE_LS,
    DRV8323_REG_OCP,
    DRV8323_REG_CSA
};


static const uint16_t expected_data[] =
{
    0x000U,
    0x3FFU,
    0x7FFU,
    0x159U,
    0x283U
};


/**
 * @brief  Read one DRV8323 register.
 *
 * @param  addr  Register address (0x00 ~ 0x06)
 * @param  data  Pointer used to return register data
 *
 * @return HAL_OK / HAL_ERROR / HAL_TIMEOUT ...
 */
HAL_StatusTypeDef DRV8323_ReadReg(uint8_t addr,
                                  uint16_t *data)
{
    uint16_t tx_data;
    uint16_t rx_data;

    HAL_StatusTypeDef status;


    tx_data =
        DRV8323_READ |
        ((addr << DRV8323_ADDR_SHIFT) &
         DRV8323_ADDR_MASK);


    HAL_GPIO_WritePin(
        SPI1_CS_GPIO_Port,
        SPI1_CS_Pin,
        GPIO_PIN_RESET
    );


    status = HAL_SPI_TransmitReceive(
        &hspi1,
        (uint8_t *)&tx_data,
        (uint8_t *)&rx_data,
        1U,
        100U
    );


    while(HAL_SPI_GetState(&hspi1)
          != HAL_SPI_STATE_READY)
    {

    }


    HAL_GPIO_WritePin(
        SPI1_CS_GPIO_Port,
        SPI1_CS_Pin,
        GPIO_PIN_SET
    );


    *data = rx_data;


    return status;
}


/**
 * @brief  Write one DRV8323 register.
 *
 * @param  addr  Register address
 * @param  data  11-bit register data
 *
 * @return HAL_OK / HAL_ERROR / HAL_TIMEOUT ...
 */
HAL_StatusTypeDef DRV8323_WriteReg(uint8_t addr, uint16_t data)
{
    uint16_t tx_data;
    uint16_t rx_dummy;

    HAL_StatusTypeDef status;


    tx_data = DRV8323_WRITE |
              ((addr << DRV8323_ADDR_SHIFT) &
               DRV8323_ADDR_MASK) |
              (data & DRV8323_DATA_MASK);


    HAL_GPIO_WritePin(SPI1_CS_GPIO_Port,
                      SPI1_CS_Pin,
                      GPIO_PIN_RESET);


    status = HAL_SPI_TransmitReceive(&hspi1,
                                     (uint8_t *)&tx_data,
                                     (uint8_t *)&rx_dummy,
                                     1,
                                     100);


    while(HAL_SPI_GetState(&hspi1)
          != HAL_SPI_STATE_READY)
    {

    }


    HAL_GPIO_WritePin(SPI1_CS_GPIO_Port,
                      SPI1_CS_Pin,
                      GPIO_PIN_SET);


    return status;
}


/**
 * @brief  Check DRV8323 SPI communication using
 *         power-on default register values.
 *
 * @param  error  Used to return detailed mismatch information
 *
 * @return DRV8323_CHECK_OK
 *         DRV8323_CHECK_SPI_ERROR
 *         DRV8323_CHECK_VALUE_ERROR
 */
DRV8323_CheckStatus_t DRV8323_CheckSPI(
    DRV8323_CheckError_t *error)
{
    uint16_t data;

    const uint8_t count =
        sizeof(check_addr) / sizeof(check_addr[0]);


    for (uint8_t i = 0U; i < count; i++)
    {
        /*
         * First determine whether SPI communication itself
         * completed successfully.
         */
        if (DRV8323_ReadReg(check_addr[i], &data) != HAL_OK)
        {
            if (error != NULL)
            {
                error->addr     = check_addr[i];
                error->actual   = 0U;
                error->expected = expected_data[i];
            }

            return DRV8323_CHECK_SPI_ERROR;
        }


        /*
         * SPI completed, but check whether the returned
         * register value is correct.
         */
        if (data != expected_data[i])
        {
            if (error != NULL)
            {
                error->addr     = check_addr[i];
                error->actual   = data;
                error->expected = expected_data[i];
            }

            return DRV8323_CHECK_VALUE_ERROR;
        }
    }


    return DRV8323_CHECK_OK;
}